apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "lightlytics.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "lightlytics.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.lightlytics.replicas }}
  selector:
    matchLabels:
  {{- include "lightlytics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "lightlytics.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "lightlytics.serviceAccountName" . }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - name: lightlytics-agent
          image: {{ template "lightlytics.image-path" . }}
          imagePullPolicy: {{ .Values.lightlytics.image.pullPolicy }}
          resources:
{{ toYaml .Values.lightlytics.resources | indent 12 }}
          securityContext:: true
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                 drop:
                    - all
                 add:
                    - NET_BIND_SERVICE
          readinessProbe:
             tcpSocket:
                port: {{ .Values.lightlytics.port | quote }}
             initialDelaySeconds: 5
             periodSeconds: 10
          livenessProbe:
             tcpSocket:
                port: {{ .Values.lightlytics.port | quote }}
             initialDelaySeconds: 15
             periodSeconds: 20
          env:
            - name: LIGHTLYTICS_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "lightlytics.fullname" . }}
                  key: api-key
            - name: LIGHTLYTICS_API_URL
              value: {{ .Values.lightlytics.apiUrl | quote }}

            - name: FULL_SCAN_SCHEDULE_SECONDS
              value: {{ .Values.lightlytics.fullScanScheduleSeconds | quote }}

            - name: FILTER_RUNNING_PODS
              value: {{ .Values.lightlytics.filterRunningPods | quote }}

            - name: FIELD_SELECTORS_NAMESPACES
              value: {{ .Values.lightlytics.fieldSelectorsNamespaces | quote }}
              
            - name: WORKFLOW
              value: {{ .Values.lightlytics.workflow | quote }}
              
            - name: PORT
              value: {{ .Values.lightlytics.port | quote }}
              
            {{- range $envVarName, $envVarValue := $.Values.lightlytics.env }}
            - name: {{ $envVarName }}
              value: {{ $envVarValue | quote }}
            {{- end }}
